name: unstable

on:
  push:
    branches:
      - main
    tags:
      - ciflow/unstable/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  # There must be at least one job here to satisfy GitHub action workflow syntax
  introduction:
    if: github.repository_owner == 'pytorch'
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Introduce PyTorch unstable workflow
        run: |
          echo "PyTorch unstable workflow is used to host experimental or flaky jobs"
          echo " that needs to be run for every commit, but doesn't block PR merging"
          echo " as part of the stable pull or trunk workflows."
          echo
          echo "In addition, a new label called ciflow/unstable can be attached to the"
          echo " PR to trigger this workflow. That can be done either manually or"
          echo " automatically using PyTorch auto-label bot."
          echo
          echo "Once the jobs are deemed stable enough (% red signal < 5% and TTS < 3h),"
          echo " they can graduate and move back to pull or trunk."

  target-determination:
    if: github.repository_owner == 'pytorch'
    name: before-test
    uses: ./.github/workflows/target_determination.yml
    permissions:
      id-token: write
      contents: read

  get-label-type:
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    if: ${{ (github.event_name != 'schedule' || github.repository == 'pytorch/pytorch') && github.repository_owner == 'pytorch' }}
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}

  # See job-filter.yml for rules on adding job filter conditions
  job-filter:
    if: github.repository_owner == 'pytorch'
    name: job-filter
    uses: ./.github/workflows/job-filter.yml
    with:
      jobs-to-include: ${{ github.event.inputs.jobs-to-include || '' }}

  linux-jammy-rocm-py3_10-build:
    name: linux-jammy-rocm-py3.10-mi355
    uses: ./.github/workflows/_linux-build.yml
    needs:
      - get-label-type
      - job-filter
    with:
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      build-environment: linux-jammy-rocm-py3.10-mi355
      docker-image-name: ci-image:pytorch-linux-jammy-rocm-n-py3
      # TODO (huydhn): Add this back once other workflow migrates
      # sync-tag: rocm-build
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 6, runner: "linux.rocm.gpu.gfx950.1" },
          { config: "default", shard: 2, num_shards: 6, runner: "linux.rocm.gpu.gfx950.1" },
          { config: "default", shard: 3, num_shards: 6, runner: "linux.rocm.gpu.gfx950.1" },
          { config: "default", shard: 4, num_shards: 6, runner: "linux.rocm.gpu.gfx950.1" },
          { config: "default", shard: 5, num_shards: 6, runner: "linux.rocm.gpu.gfx950.1" },
          { config: "default", shard: 6, num_shards: 6, runner: "linux.rocm.gpu.gfx950.1" },
          { config: "distributed", shard: 1, num_shards: 3, runner: "linux.rocm.gpu.gfx950.2" },
          { config: "distributed", shard: 2, num_shards: 3, runner: "linux.rocm.gpu.gfx950.2" },
          { config: "distributed", shard: 3, num_shards: 3, runner: "linux.rocm.gpu.gfx950.2" },
        ]}
      use-arc: ${{ needs.get-label-type.outputs.use-arc == 'true' }}
      python-version: "3.10"
    secrets: inherit

  linux-jammy-rocm-py3_10-test:
    name: linux-jammy-rocm-py3.10-mi355
    uses: ./.github/workflows/_rocm-test.yml
    needs:
      - linux-jammy-rocm-py3_10-build
      - target-determination
      - job-filter
    with:
      build-environment: ${{ needs.linux-jammy-rocm-py3_10-build.outputs.build-environment }}
      docker-image: ${{ needs.linux-jammy-rocm-py3_10-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-jammy-rocm-py3_10-build.outputs.test-matrix }}
      tests-to-include: ${{ github.event.inputs.tests-to-include || '' }}
    secrets: inherit
